#cloud-config
autoinstall:
  version: 1
  locale: "en_US"
  timezone: "America/Port_of_Spain"
  keyboard:
    layout: us
  source:
    id: ubuntu-desktop-minimal
  storage:
    layout:
      name: lvm
  identity:
    realname: CreativeNull
    username: creativenull
    hostname: nullmachine
    password: "$1$MkOTatcl$0F0RuBUBXd2UfzWOe5q4b/"
  packages:
    - git
    - curl
    - wget
