#!/usr/bin/env bash
set -e

echo '---'
echo 'Linking config files'
echo '---'

rm -rf ~/.config/kitty
ln -s ~/dotfiles/config/kitty ~/.config/

rm -fv ~/.gitconfig
ln -s ~/dotfiles/gitconfig ~/.gitconfig

rm -fv ~/.zshrc
ln -s ~/dotfiles/zshrc ~/.zshrc

rm -rfv ~/.config/zsh-plugins
ln -s ~/dotfiles/config/zsh-plugins ~/.config/

rm -fv ~/.config/starship.toml
ln -s ~/dotfiles/config/starship.toml ~/.config/starship.toml

rm -fv ~/.config/lsd
ln -s ~/dotfiles/config/lsd ~/.config/

rm -fv ~/.config/nvim
ln -s ~/dotfiles/config/nvim ~/.config/

echo ''
echo '---'
echo 'Linking npm packages and installing'
echo '---'

rm -fv ~/.npmrc
ln -s ~/dotfiles/npmrc ~/.npmrc

rm -fv ~/.default-npm-packages
ln -s ~/dotfiles/default-npm-packages ~/.default-npm-packages

read -p "Install global npm packages? (y/N) " choice

if [ "$choice" = "y" ]; then
    if [ -x "$(command -v npm)" ]; then
	npm install -g $(cat ~/.default-npm-packages)
    fi
fi

read -p "Change default shell? (y/N) " choice

if [ "$choice" = "y" ]; then
    echo '---'
    echo 'Setting default shell to zsh'
    echo '---'

    chsh -s /bin/zsh
fi
