GOOSE_PROVIDER: openrouter
GOOSE_MODEL: moonshotai/kimi-k2.5
GOOSE_CLI_MIN_PRIORITY: 0.8
GOOSE_MODE: auto
SECURITY_PROMPT_ENABLED: true
extensions:
  developer:
    enabled: true
    type: builtin
    name: developer
    description: Code editing and shell access
    display_name: Developer Tools
    timeout: 60
    bundled: true
    available_tools: []
  chatrecall:
    enabled: false
    type: platform
    name: chatrecall
    description: Search past conversations and load session summaries for contextual memory
    display_name: Chat Recall
    bundled: true
    available_tools: []
  apps:
    enabled: true
    type: platform
    name: apps
    description: Create and manage custom Goose apps through chat. Apps are HTML/CSS/JavaScript and run in sandboxed windows.
    display_name: Apps
    bundled: true
    available_tools: []
  code_execution:
    enabled: false
    type: platform
    name: code_execution
    description: Goose will make extension calls through code execution, saving tokens
    display_name: Code Mode
    bundled: true
    available_tools: []
  skills:
    enabled: true
    type: platform
    name: skills
    description: Load and use skills from relevant directories
    display_name: Skills
    bundled: true
    available_tools: []
  todo:
    enabled: true
    type: platform
    name: todo
    description: Enable a todo list for goose so it can keep track of what it is doing
    display_name: Todo
    bundled: true
    available_tools: []
  extensionmanager:
    enabled: true
    type: platform
    name: Extension Manager
    description: Enable extension management tools for discovering, enabling, and disabling extensions
    display_name: Extension Manager
    bundled: true
    available_tools: []
  tom:
    enabled: false
    type: platform
    name: tom
    description: Inject custom context into every turn via GOOSE_MOIM_MESSAGE_TEXT and GOOSE_MOIM_MESSAGE_FILE environment variables
    display_name: Top Of Mind
    bundled: true
    available_tools: []
  summon:
    enabled: true
    type: platform
    name: summon
    description: Load knowledge and delegate tasks to subagents
    display_name: Summon
    bundled: true
    available_tools: []
GOOSE_TELEMETRY_ENABLED: false
GOOSE_CLI_LIGHT_THEME: 'Catppuccin Latte'
GOOSE_CLI_DARK_THEME: 'TwoDark'
